name: Build 3DS Game

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install 3DS Libraries
        run: |
          # On installe le groupe complet pour ne rien oublier
          dkp-pacman -S --noconfirm 3ds-dev

      - name: Build project
        run: |
          make
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrafficRacer-3DS
          path: |
            *.3dsx
